runtime:
  precision:
    model_dtype: fp32
    autocast_dtype: bf16
  fsdp:
    enabled: true
    sharding_strategy: FULL_SHARD
    use_orig_params: true
    limit_all_gathers: true

data:
  train_paths: /data1021/xukaichen/data/CTA/pbmc.h5ad
  shuffle_train_paths: false
  shuffle_train_paths_seed: 0
  batch_size: 32
  num_workers: 0
  pin_memory: true
  drop_last: false
  max_length: 2048
  gene_key: null
  platform_key: assay
  species_key: null
  tissue_key: tissue
  disease_key: disease
  expr_pad_value: 0.0
  condition_mask:
    enabled: false
    unk_ratio: 0.0
  token_dict_path: resources/token_dict.csv
  cond_dict_path: resources/cond_dict.csv
  human_tfs_path: resources/human_tfs.csv
  mouse_tfs_path: resources/mouse_tfs.csv
  preprocess:
    enabled: true
    min_genes: 200
    min_cells: 3
    max_pct_counts_mt: 20.0
    target_sum: 10000.0
    log1p: true
    n_top_genes: 2000
    hvg_flavor: seurat
    subset_hvg: true
    remove_mito_genes: true
    remove_ribo_genes: true
    remove_hb_genes: true
    sanitize_X: true
    X_fill_value: 0.0
    inplace: false

evaluator:
  checkpoint_path: checkpoints/sfm_latest.pt
  evaluation_grn_path: /data1021/xukaichen/data/GRN/networks/hSTRING.csv
  foundation_name: sfm
