model_source: assets

runtime:
  precision:
    model_dtype: fp32
    autocast_dtype: bf16
  fsdp:
    enabled: true
    sharding_strategy: FULL_SHARD
    use_orig_params: true
    limit_all_gathers: true

data:
  # Each entry can be a `.h5ad` file or a directory; directories are expanded to all nested `.h5ad` files.
  train_paths: /scratch/kxu248/data/Atlas/
  shuffle_train_paths: true
  shuffle_train_paths_seed: 0
  batch_size: 16
  gradient_accumulation_steps: 8
  num_workers: 0
  pin_memory: false
  drop_last: false
  max_length: 2048
  gene_key: feature_id
  platform_key: assay
  species_key: species
  tissue_key: tissue
  disease_key: disease
  expr_pad_value: 0.0
  condition_vocab:
    regenerate: True
  condition_mask:
    enabled: true
    unk_ratio: 0.1
  preprocess:
    enabled: true
    min_genes: 200
    min_cells: 3
    max_pct_counts_mt: 20.0
    target_sum: 10000.0
    log1p: true
    n_top_genes: 2000
    hvg_flavor: seurat
    subset_hvg: true
    remove_mito_genes: true
    remove_ribo_genes: true
    remove_hb_genes: true
    sanitize_X: true
    X_fill_value: 0.0
    inplace: false

optimizer:
  name: adamw
  lr: 0.0001
  betas: [0.9, 0.95]
  eps: 1.0e-8
  weight_decay: 0.01

scheduler:
  name: cosine_with_warmup
  warmup_ratio: 0.03
  min_lr_ratio: 0.1

loss:
  foundation_name: sfm
  head_name: vgae
  elbo:
    enabled: true
  prior:
    enabled: true
    kwargs:
      pos_weight: 20.0
      neg_weight: 1.0
      neg_sample_ratio: 5.0
    weight_schedule:
      initial: 10.0
      final: 0.1
      span_epochs: null
  dag:
    enabled: true
    kwargs:
      lambda_dag: 1.0

trainer:
  epochs: 1
  grad_clip_norm: 1.0
  save_every_epochs: 1
